### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by 37integer** [SerezD/NVAE-from-scratch#1]
when i run sample_random_images.py, it will have error:
Traceback (most recent call last):
  File "/workshop/NVAE-from-scratch/src/scripts/sample_random_images.py", line 78, in <module>
    sample(parse_args())
  File "workshop/NVAE-from-scratch/src/scripts/sample_random_images.py", line 58, in sample
    model.load_state_dict(checkpoint[f'state_dict_temp={args.temperature}'])
KeyError: 'state_dict_temp=1.0'

then i check the key inside the checkpoint:
epoch
global_step
configuration
state_dict
optimizer
grad_scaler

 no key's name is 'state_dict_temp'.

**Comment by 37integer** [comment]
solved, sorry i didn't see need do  update_bn_stats.py firstly

**Comment by SerezD** [comment]
Yes, that is because the paper suggests updating BN statistics before sampling. Instead of doing it every time before sampling, I decided to save the updated checkpoint once and for all. 

This solution has the drawback that you need to save a copy of the model for each sampling temperature, but it avoids to waste time every time you need to sample some images.
